DIRECTORY: ../TestData/bulkData/
TIEMOUT: 15
FILES:
  - name: tst40M.txt 
    size: 41943040 # File size in bytes
  - name: tst2.txt
    size: 1024*20

SITES: # Destintation SitesList
  CEPH-SVC01:
      - ceph-svc01.gridpp.rl.ac.uk
      - dteam:/test/
      - 1094
  # CEPH-SVC02:
      # - ceph-svc02.gridpp.rl.ac.uk
      # - dteam:/test/
#   CEPH-C04: 
#       - ceph-c04.glasgow.ac.uk
#       - dteam:/test/ 
#   GOLIAS100: 
#       - se1.farm.particle.cz #golias100.farm.particle.cz - same site
#       - dpm/farm.particle.cz/home/dteam/test/
#   DC2-GRID-64: 
#       - dc2-grid-64.brunel.ac.uk
#       - dpm/brunel.ac.uk/home/dteam/test/
  # ATLAS:
  #     - atlas-auth.web.cern.ch
  #     - dteam:test/
  #     - 1094
  # LCG-SE01: 
  #     - lcg-se01.icepp.jp
  #     - dpm/icepp.jp/home/dteam/test/    

