TIMEOUT: 10

TEST_ENDPOINT: # SiteA - site tested against UK and Non-UK sites
    CEPH-SVC16:
        - ceph-svc16.gridpp.rl.ac.uk 
        - dteam:/test/

UK_SITE: # SiteB
    # CEPH-SVC28:
    #     - ceph-svc28.gridpp.rl.ac.uk
    #     - dteam:/test/
    CEPH-C04: 
        - ceph-c04.glasgow.ac.uk
        - dteam:/test/ 

NON_UK_SITE: # SiteB
    GOLIAS100: 
        - se1.farm.particle.cz #golias100.farm.particle.cz - same site
        - dpm/farm.particle.cz/home/dteam/test/
    # DC2-GRID-64: 
    #     - dc2-grid-64.brunel.ac.uk
    #     - dpm/brunel.ac.uk/home/dteam/test/
    # LCG-SE01: 
    #     - lcg-se01.icepp.jp
    #     - dpm/icepp.jp/home/dteam/test/


