title: "XRootD Testing Framework Documentation"
description: "Documentation for the XRootD testing framework for pre-deployed endpoints"
baseurl: "/xrootd-testing-framework"  # If your pages are under the `docs/` folder
permalink: "/:path/"  # Makes URLs simpler

theme: minima
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme

# Specify where navigation data is stored
data_dir: "_data"

# Enable Markdown support for GitHub Pages
markdown: kramdown
show_sidebar: true
search: true

# Navigation links
rtd_nav_links:
- title: "Home"
  url: "/xrootd-testing-framework/"
- title: "Installation"
  url: "/xrootd-testing-framework/installation"
- title: "Classes and Methods"
  url: "/xrootd-testing-framework/classes-and-methods"
- title: "Config File Setup"
  url: "/xrootd-testing-framework/config-file-setup"
- title: "How To Setup A Test"
  url: "/xrootd-testing-framework/setup-test-tutorial"
- title: "Examples Of Tests"
  url: "/xrootd-testing-framework/examples"
