title: "XRootD Testing Framework Documentation"
description: "Documentation for the XRootD testing framework for pre-deployed endpoints"
baseurl: "/docs"  # If your pages are under the `docs/` folder
permalink: "/:path/"  # Makes URLs simpler

remote_theme: "squidfunk/jekyll-rtd-theme"
plugins:
- jekyll-remote-theme
- jekyll-github-metadata
- jekyll-seo-tag
- jekyll-coffeescript
- jekyll-commonmark-ghpages
- jekyll-gist
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings

# Specify where navigation data is stored
data_dir: "_data"

# Enable Markdown support for GitHub Pages
markdown: kramdown
show_sidebar: true
search: true

# Navigation links
rtd_nav_links:
  - title: "Home"
    url: "/docs/"
  - title: "Introduction"
    url: "/docs/introduction"
  - title: "Setup"
    url: "/docs/setup"
  - title: "Classes and Methods"
    url: "/docs/classes-and-methods"
  - title: "How to setup a test"
    url: "/docs/setup-test-tutorial"
  - title: "Examples"
    url: "/docs/examples"
